displayName: Hasura security plugins
type: middleware
iconPath: .github/logo.png

summary: "Traefik plugin to ensure some security with hasura"

import: github.com/albttx/traefik-plugin-sec-hasura

testData:
  GraphQLPath: "/v1/graphql"
  IgnoreHeaders: ["x-hasura-admin-secret"]
